version: '3'

services:
  #
  # Project reverse proxy
  nginx-proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - pgadmin
      - filebrowser
    build:
      context: ./data/proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=hop.elasticlabs.co
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - elabs-revproxy

  #
  # -> PostGIS
  postgis:
    image: kartoza/postgis:${POSTGIS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_postgis
    restart: on-failure
    expose:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - FORCE_SSL=FALSE
    volumes:
      - postgis-data:/var/lib/postgresql
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
    networks:
      - elabs-revproxy
  
  # -> pgAdmin
  pgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    restart: always
    build:
      context: ./config/pgadmin
    expose:
      - "5050:80"
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - elabs-revproxy

  # -> Apache Hop Web
  hop-web:
    container_name: ${COMPOSE_PROJECT_NAME}_hop-web
    restart: always
    image: apache-hop/web:latest
    expose:
      - "8080"
    depends_on:
      - postgis
      - proxy
    networks:
      - elabs-revproxy

  # -> Metabase
  metabase:
    container_name: ${COMPOSE_PROJECT_NAME}_metabase
    restart: always
    image: metabase/metabase:latest
    expose:
      - "3000"
    depends_on:
      - postgis
      - proxy
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${POSTGRES_DB}
      - MB_DB_PORT=5432
      - MB_DB_USER=${POSTGRES_USER}
      - MB_DB_PASS=${POSTGRES_PASS}
      - MB_DB_HOST=postgis
    networks:
      - elabs-revproxy

volumes:
  vhost.d:
  homepage-public:
  portainer-data:
  mviewer-base:
  # -> postgis
  postgis-data:
  pgadmin-data:
  # -> geoserver
  geoserver-data:
  geoserver-injected-data:
  geoserver-settings:

networks:
  elabs-revproxy:
    name: ${APPS_NETWORK}
    external: true
    ipam:
      config:
        - subnet: "172.24.0.0/16"
